### ISSUE TITLE
Provide documentation for the implementation

### ISSUE THREAD

**Issue by shresthaankit7** [agitlin/odata#2]
I'm stuck in the implementation for the integration of odata in my grails application.
The only good reference i was able to get is from the links provided from stack-over flow link [here](https://stackoverflow.com/questions/16514469/how-do-you-expose-a-grails-domain-model-using-odata) and official odata tutorial [here](https://olingo.apache.org/doc/odata4/tutorials/read/tutorial_read.html#431-create-and-implement-the-servlet).

Then this repository has some potential options but i can't find any documentation. 
Can you please provide one?

**Comment by agitlin** [comment]
Sorry, man. It's been a long time ago and we never bothered to create documentation then. I don't think I will remember anything now. good luck.
